<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="HPaf008ax" name="com.guru99.testCases.tc_01_LoginTest" tests="5" failures="1" timestamp="2020-10-22T18:20:37 IST" time="114.983" errors="0">
  <testcase name="verifyTitle" time="49.881" classname="com.guru99.testCases.tc_01_LoginTest">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.guru99.testCases.tc_01_LoginTest.verifyTitle(tc_01_LoginTest.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verifyTitle -->
  <system-out/>
  <testcase name="invalidLoginTest" time="3.476" classname="com.guru99.testCases.tc_01_LoginTest"/>
  <system-out/>
  <testcase name="validLoginTest" time="3.950" classname="com.guru99.testCases.tc_01_LoginTest"/>
  <system-out/>
  <testcase name="invalidLoginTest" time="53.645" classname="com.guru99.testCases.tc_01_LoginTest"/>
  <system-out/>
  <testcase name="invalidLoginTest" time="4.031" classname="com.guru99.testCases.tc_01_LoginTest"/>
  <system-out/>
</testsuite> <!-- com.guru99.testCases.tc_01_LoginTest -->
